#!C:\Users\hp\PycharmProjects\Face_recog\Scripts\python.exe

from dipy.workflows.flow_runner import run_flow
from dipy.workflows.mask import MaskFlow

if __name__ == "__main__":
    run_flow(MaskFlow())
