#!C:\Users\hp\PycharmProjects\Face_recog\Scripts\python.exe

from dipy.workflows.flow_runner import run_flow
from dipy.workflows.reconst import ReconstIvimFlow

if __name__ == "__main__":
    run_flow(ReconstIvimFlow())
