#!C:\Users\hp\PycharmProjects\Face_recog\Scripts\python.exe

from dipy.workflows.flow_runner import run_flow
from dipy.workflows.viz import HorizonFlow

if __name__ == "__main__":
    run_flow(HorizonFlow())
